### ISSUE TITLE
Manejo de Descuentos en Impresión Fiscal

### ISSUE THREAD

**Issue by emmie** [comitsrl/lar_361#24]
En caso de existir un descuento realizado en el POS, reflejar dicho descuento en la impresión fiscal como "Descuento General".

**Comment by mzuniga** [comment]
Comportamiento del controlador fiscal al aplicar descuentos sobre Impuestos Internos:
* Si el valor del factor k es diferente de cero y va precedido por el signo ‘+’, el
         * monto del impuesto interno es fijo. Los impuestos internos fijos no son afectados
         * por recargos o descuentos posteriores. 
         * Textual del Manual de comandos fiscales -
         * Impresoras Fiscales HASAR SMH/P-615F , SMH/P-PR4F , SMH/P-950F , SMH/P-951F
         * SMH/P-715F versiones 1.00, 2.01, 3.02, y 4.03 SMH/P-PR5F versiones 1.00 y 2.01
         * SMH/P-441F versión 1.00
Se agrega la funcionalidad para permitir agregar el prefijo + cuando sea necesario: 695a0f6
